<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_preprocess_node().
 */
function glossary_tooltip_preprocess_node(&$variables) {

  // Attach library to node.
  $variables['#attached']['library'][] = 'glossary_tooltip/glossary_tooltip';

  // Get all glossary terms.
  $terms_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $terms = $terms_storage->loadTree('glossary');

  $glossary_items = [];

  // Form array of glossaries to pass them to js.
  foreach ($terms as $term) {
    $term_entity = $terms_storage->load($term->tid);
    if (!$term_entity instanceof TermInterface) {
      continue;
    }
    $glossary_items[] = [
      'name' => $term_entity->getName(),
      'description' => $term_entity->get('field_description')->value ?? '',
      'url' => $term_entity->toUrl()->toString()
    ];
  }

  $variables['#attached']['drupalSettings']['glossaryItems'] = $glossary_items;

}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function glossary_tooltip_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  // Clear cache when glossary is updated.
  $build['#cache']['tags'][] = 'taxonomy_term_list:glossary';
}
